services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: crypto-app:latest
    depends_on:
      - influxdb
    env_file:
      - ./.env
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning



volumes:
  influxdb:
  grafana:
